### ISSUE TITLE
Results of different datasets

### ISSUE THREAD

**Issue by KarenMars** [Feaxure-fresh/TL-Bearing-Fault-Diagnosis#11]
Hi, your work is awesome! I wonder whether you can provide a summary of results on different bearing fault diagnosis datasets attached in this repository. Thank you very much : )

**Comment by Feaxure-fresh** [comment]
We have not considered providing accuracy result tables for all methods at this time, due to two main reasons:
1. Different individuals use datasets in various ways. Many datasets lack a standardized approach for transfer scenarios, so researchers often create their own transfer cases. This results in training outcomes for a specific implementation that are not representative.
2. Some methods included in this resource were not implemented with full details outlined in their respective papers. And some more complex basic network structures (such as Resnet, etc.) may bring better training results. Therefore, the performance of these methods may not be entirely accurate or satisfactory.
